#!/bin/bash
# Bring up the rdo_kitsu processor stack pointed at the LOCAL AYON + LOCAL Kitsu.
#
# Run this AFTER the databases have been restored and localize_kitsu_addon.py has
# pointed the add-on settings at the local Kitsu. Order matters: the processor reads
# the Kitsu URL/token from AYON settings at startup and raises if they are unset.
#
#   1. sudo scripts/sync-and-restore-databases.sh
#   2. python -m gishant_scripts.ayon.localize_kitsu_addon --apply
#   3. ./up-local-stack.sh            <-- this script
#
# Regenerates .env.local from ayon-server/.env on every run, so the API key is never
# committed and never goes stale.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PROCESSOR_COMPOSE="${PROCESSOR_COMPOSE:-$HOME/dev/repos/rdo-ayon-kitsu/services/processor/docker-compose.yml}"
OVERRIDE_COMPOSE="$HERE/docker-compose.local.yml"
AYON_ENV="${AYON_ENV:-$HERE/../ayon-server/.env}"
ENV_LOCAL="$HERE/.env.local"
PROJECT_NAME="rdo-kitsu-processor-local"

NC='\033[0m'; RED='\033[0;31m'; GREEN='\033[0;32m'; BLUE='\033[0;34m'
log()     { echo -e "  ${BLUE}i${NC}  $*"; }
success() { echo -e "  ${GREEN}✓${NC}  ${GREEN}$*${NC}"; }
error()   { echo -e "  ${RED}✗${NC}  ${RED}$*${NC}" >&2; }

for f in "$PROCESSOR_COMPOSE" "$OVERRIDE_COMPOSE" "$AYON_ENV"; do
    if [[ ! -f "$f" ]]; then
        error "Required file not found: $f"
        exit 1
    fi
done

# ── Read the local AYON API key ────────────────────────────────────────────────
# Parsed rather than sourced: ayon-server/.env holds unrelated secrets we do not want
# leaking into this shell's environment.
# Prefer an injected key (the orchestrator passes gisi's login token); else read the
# service key from ayon-server/.env.
AYON_API_KEY="${AYON_API_KEY:-$(grep -E '^[[:space:]]*AYON_API_KEY=' "$AYON_ENV" | tail -1 | cut -d= -f2- | tr -d '"'"'"'' | xargs || true)}"

if [[ -z "$AYON_API_KEY" ]]; then
    error "AYON_API_KEY not found in $AYON_ENV"
    exit 1
fi

AYON_SERVER_URL="${AYON_SERVER_URL:-http://10.1.69.24:5000}"
case "$AYON_SERVER_URL" in
    *host.docker.internal*|*localhost*|*127.0.0.1*|*10.1.69.24*) ;;
    *)
        error "AYON_SERVER_URL looks non-local ($AYON_SERVER_URL) - refusing to start."
        exit 1
        ;;
esac

# ── Generate .env.local (never committed) ──────────────────────────────────────
log "Writing $ENV_LOCAL"
umask 077
cat > "$ENV_LOCAL" <<ENVEOF
# GENERATED by up-local-stack.sh -- do not commit, do not edit by hand.
AYON_SERVER_URL=$AYON_SERVER_URL
AYON_API_KEY=$AYON_API_KEY
AYON_ADDON_NAME=${AYON_ADDON_NAME:-rdo_kitsu}
AYON_ADDON_VERSION=${AYON_ADDON_VERSION:-0.3.3}
SYNC_INTERVAL=${SYNC_INTERVAL:-30}
ENVEOF
chmod 600 "$ENV_LOCAL"
success "Wrote $ENV_LOCAL (0600, API key sourced from ayon-server/.env)"

compose() {
    docker compose \
        -p "$PROJECT_NAME" \
        -f "$PROCESSOR_COMPOSE" \
        -f "$OVERRIDE_COMPOSE" \
        --env-file "$ENV_LOCAL" \
        "$@"
}

# ── Validate before touching anything ─────────────────────────────────────────
log "Validating merged compose config..."
compose config --quiet
success "Compose config is valid"

if [[ "${1:-}" == "--config-only" ]]; then
    log "--config-only given; not starting anything."
    exit 0
fi

log "Starting processor stack (project: $PROJECT_NAME)..."
compose up -d

success "Processor stack is up. Follow logs with:"
echo "    docker compose -p $PROJECT_NAME -f $PROCESSOR_COMPOSE -f $OVERRIDE_COMPOSE --env-file $ENV_LOCAL logs -f listener consumer"
